### ISSUE TITLE
서버 없이 앱을 만들 수 있을까?

### ISSUE THREAD

**Issue by doublemetal** [organic-benefit/eternal-household-account#1]
html, css, javascript 로 동작하는 앱을 구현했다. 브라우저로 서버에 접근해 resouces 를 다운 받아 구동하는 방법 말고 다른 것이 있을까?

**Comment by doublemetal** [comment]
예를 들면, windows 에서의 electron 이나 PhoneGap 등의 프레임워크로 패키징하는 방식이 있다.
=> 타겟 디바이스는 모바일이므로 PhoneGap 같은 패키징 방식은 적절하지 않다. (구린 것 같다)

**Comment by doublemetal** [comment]
Firebase : https://firebase.google.com/pricing/?authuser=0
github page

**Comment by serivires** [comment]
heroku: https://www.heroku.com/pricing

**Comment by serivires** [comment]
가계부인 만큼 개인정보 보안이 중요해 보이네요.

**Comment by songeunwoo** [comment]
![image](https://user-images.githubusercontent.com/16470009/35907841-63c06ddc-0c32-11e8-8127-a2acb7dfdf2a.png)

heroku 멋지네요

**Comment by songeunwoo** [comment]
Firebase에는 인증도 지원을 해주네요

**Comment by jjc89** [comment]
구글이 밀고나가는만큼 firebase 좀 핫해보입니다. 이쪽에서도 취미로 firebase 이용해서 웹앱 만드시는분 봤습니다.

**Comment by serivires** [comment]
[파이어베이스를 실제 모바일 백엔드로 사용하면 일어날 수 있는 일들](https://academy.realm.io/kr/posts/firebase-as-a-real-mobile-backend/)

**Comment by songeunwoo** [comment]
![image](https://user-images.githubusercontent.com/16470009/35951171-948edec2-0cbd-11e8-9257-4ac92f123042.png)

기대되네요 geunwoo project!!!!

**Comment by songeunwoo** [comment]
최근 pasta 에서도
https://serverless.com/ 와 wsk, lamdba 로 배포 자동화를 구축했습니다.

mattermost 웹챗을 이용해서 빌드 머지 태깅 tts등록 종료까지 하는 방식인데요.
이젠  serverless가 대세가 되는듯 하네요.

**Comment by serivires** [comment]
@songeunwoo  서버 없어지면.. 우리들은 뭘먹고 살아야 할까요.

**Comment by doublemetal** [comment]
serverless 와 serivires 라니 궁합이 잘 맞아 보이네요.
사실 제가 제일 원했던 건 리소스형태의 로컬앱이었는데요. (윈도에서 html 파일과 브라우저만으로 동작하는 앱을 상상해보세요) 안드로이드는 모르겠으나 ios 에서는 이래저래 제약 사항이 있어서 힘들어 보입니다. 파이어베이스 한 번 끄적여 봐야겠어요.

**Comment by serivires** [comment]
@doublemetal 원하신게 이런건가요?
 서버 없이 동작되는 스크립트앱
https://tiddlywiki.com
https://github.com/Jermolene/TiddlyWiki5

**Comment by serivires** [comment]
이 issue는 그만 close 하시죠.

**Comment by doublemetal** [comment]
코어 엔진 만들 생각을 하니 오히려 클라이언트 앱을 만드는 게 장점이 많을 거 같아요
